Repository ucsb-cs156-s23/proj-happycows-s23-6pm-4, pull requests merged in 2023-06, with the labels that each got.

#37 Yuki - Added test coverage for current milk price
  frontend/src/tests/components/Commons/CommonsOverview.test.js
Labels: FIXME-Needs peer CR

#38 Added toast message for Testing Jobs
  frontend/src/main/pages/AdminJobsPage.js
Labels: s23-6pm-4

#39 pc - update workflow 33 to publish stryker report even if coverage is below 100%
  .github/workflows/33-frontend-pr-mutation-testing.yml
Labels: staff

#44 Yuki - Fix current milk price test
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
Labels: 5

#45 JessicaH - Redesign the user commons page (Make key user statistics clear)
  frontend/src/index.css
  frontend/src/main/components/Commons/FarmStats.js
Labels: 5

#49 Yuki - Update user commons and leaderboard fixtures to add totalCowsBought and totalCowsSold
  frontend/src/fixtures/leaderboardFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
Labels: 5

#46 Yuki - Add PUT endpoint for UserCommonsController to update a user commons
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateUserCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: s23-6pm-4, 10

#50 Yuki - Added total cows bought and sold to UserCommons entity
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 5

#51 Yuki - Updated UserCommonsController for total cows bought and sold
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 10

#56 JacobW Sell Multiple Cows Backend
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/FrontendProxyController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 10, Merge Candidate-ci/cd

#61 JacobW Scale Cow Sale Price Frontend Update Fixtures
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
Labels: 5, Merge Candidate-ci/cd

#68 JacobW Scale Cow Sale Price Frontend
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: 10, Merge Candidate-ci/cd

#76 JacobW Sell All Cows Button
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/tests/components/Commons/ManageCows.test.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 5, Merge Candidate-ci/cd

#78 JacobW Buy Max Cows Button
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/tests/components/Commons/ManageCows.test.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 5, Merge Candidate-ci/cd
